### ISSUE TITLE
Add a guidance of how to deploy Log Hub using other region's Cognito User Pool

### ISSUE THREAD

**Issue by JoeShi** [awslabs/log-hub#20]
### Describe the issue

There are a couple regions where Cognito User Pool is missing. However, the Cognito User Pool is a standard OpenID Connect Provider. I need a guidance, how to use the Cognito User Pool in other regions to launch the Log Hub solution.

### Links

https://awslabs.github.io/log-hub/en/implementation-guide/deployment/

**Comment by JoeShi** [comment]
Here is the guide. https://awslabs.github.io/log-hub/en/implementation-guide/deployment/with-oidc/#option-1-using-cognito-user-pool-from-another-region

**Comment by coder-xsj** [comment]
> 这是指南。https://awslabs.github.io/log-hub/en/implementation-guide/deployment/with-oidc/#option-1-using-cognito-user-pool-from-another-region

this url access 404

**Comment by JoeShi** [comment]
We recently move the repo from awslabs to aws-solutions organization. Here is the new url https://aws-solutions.github.io/log-hub/en/implementation-guide/deployment/with-oidc/#option-1-using-cognito-user-pool-from-another-region
