### ISSUE TITLE
Application Log (EKS): ingest EKS Pod logs directly to OpenSearch

### ISSUE THREAD

**Issue by wanghd89** [awslabs/log-hub#25]
### Describe the feature

Allow customers to ingest EKS Pod logs directly into OpenSearch. For customers doesn't require data buffering layer and log processor.

### Use Case

As a customer, I want to ingest EKS Pod logs directly into AOS, so that I can save cost on Data Buffer (KDS) and Log Processor(Lambda)

### Log Hub version used

1.0.0

**Comment by JoeShi** [comment]
Completed in v1.1.0
